### ISSUE TITLE
UBX-TIM-TP (0x0D 0x01) wrong format

### ISSUE THREAD

**Issue by dorsic** [sparkfun/Qwiic_Ublox_Gps_Py#12]
Field 'week' is of type U2 not I4 as declared in sparkfun_predefines.py and thus the message cannot be parsed.

**Comment by edspark** [comment]
You are correct, thank you! Fixed [in this commit](https://github.com/sparkfun/Qwiic_Ublox_Gps_Py/commit/4b585a00d1d7e6666d286ecffb817b2a5560e43e).
