### ISSUE TITLE
module_software_version() method (a.k.a. UBX-MON-VER) is broken

### ISSUE THREAD

**Issue by mgesteiro** [sparkfun/Qwiic_Ublox_Gps_Py#13]
the method to obtain module's info is broken, as the message ID for MON-VER is not declared anywhere:

`self.mon_ms.get('VER')` in [ublox_gps.py#L509](https://github.com/sparkfun/Qwiic_Ublox_Gps_Py/blob/master/ublox_gps/ublox_gps.py#L509) returns nothing.

**Comment by edspark** [comment]
It is working now. You can do something like the following:

```python
ver = gps.module_software_version()
print("Sofware, Hardware: ",  ver.swVersion, ver.hwVersion)
```

There's definitely a much better way to format it, but those are the sub-fields you're looking for.

**Comment by mgesteiro** [comment]
a little bit too late 😉

https://github.com/mgesteiro/ublox9

regards!
