### ISSUE TITLE
Setup scripts claim the library is licenced with an MIT licence

### ISSUE THREAD

**Issue by KubaFYI** [sparkfun/Qwiic_Ublox_Gps_Py#18]
It seems like there are bits of the previous licence left in `setup.py` which need to be corrected to the actually used licence. 

Related to #11

**Comment by edspark** [comment]
Fixed here: https://github.com/sparkfun/Qwiic_Ublox_Gps_Py/commit/e48b776fbe0cef7fe4360f163e5306455b032329

**Comment by KubaFYI** [comment]
> Fixed here: [e48b776](https://github.com/sparkfun/Qwiic_Ublox_Gps_Py/commit/e48b776fbe0cef7fe4360f163e5306455b032329)

Not fully. See [this line](https://github.com/sparkfun/Qwiic_Ublox_Gps_Py/blob/e48b776fbe0cef7fe4360f163e5306455b032329/setup.py#L66).

**Comment by edspark** [comment]
Thank you for catching both of those =)
