### ISSUE TITLE
Raw Data Output

### ISSUE THREAD

**Issue by shubham9436** [sparkfun/Qwiic_Ublox_Gps_Py#19]
Is it possible to get the raw data? If so, can someone please provide an example.

**Comment by shadyrobots** [comment]
check out ubxtranslator (used at the heart of this code)
https://github.com/dalymople/ubxtranslator

cls_name, msg_name, payload = parser.receive_from(port)
where payload is the raw data

or go into core.py under receive_from and tap into buff

**Comment by edspark** [comment]
Yeah I think @shadyrobots is correct, assuming that's what you intended with your question @shubham9436. Cheers!
