### ISSUE TITLE
Will i2c support ever be implemented?

### ISSUE THREAD

**Issue by tkschuler** [sparkfun/Qwiic_Ublox_Gps_Py#22]
Will i2c support ever be implemented?

If not, is there a workaround or other library that supports i2c via python with the sparkfun GPS modules?

**Comment by Ezward** [comment]
Looking for the same thing.  I have a nice shiny Sparkfun GPS-RTK2-ZED-F9P SMA. One of the reasons I bought it was that I could use quiic I2C bus.  I bought a number of quiic connectors as well.  It turns out it was a waste of money unless I can do this in Python.  Is there any plan so support I2C?

**Comment by joshjhans** [comment]
Agreed; better documentation on how to use this library with I2C would be very helpful.

**Comment by nick-elzer** [comment]
Has there been any update to this?? I need to use it with I2C and am having a rough time.

**Comment by edspark** [comment]
Sorry for the long delay - the library is currently being updated. However I can speak towards I2C. From my research, read: googling,   I2C on a raspberry pi has still yet to fully fix clock stretching. In addition u-blox modules push clock stretching to its limits; the modules hold the clock line for every single message received, and for not-insignificant amounts of time.

When there is a solid fix, please feel free to reopen this issue or create a new one.
