### ISSUE TITLE
How do I modify sampling rate?

### ISSUE THREAD

**Issue by tensorturtle** [sparkfun/Qwiic_Ublox_Gps_Py#23]
The ZED-F9P is supposed to be able to output 20hz, but when I run the example 1 python script, I get about 1hz.
How can I increase the sampling rate to be as fast as possible?

Thank you

**Comment by Ino-Ichan** [comment]
You can set the configuration by using u-center. Even when you want to use the module on Linux, you can first set the config with u-center on Windows.

Or, you can alos change the module samping Hz by sending a binary message through serial port.
https://github.com/PaulZC/F9P_RAWX_Logger/blob/master/UBX.md

I recommend the first method using u-center.

**Comment by tensorturtle** [comment]
Thank you @Ino-Ichan ! I will try it out.

**Comment by tensorturtle** [comment]
Hi @Ino-Ichan I appreciate your guidance, but the Windows application is horribly unstable (crashes every time, and I tried everything to get it to work), and I frankly have no idea how to work with the low level second method. Could you give me an example workflow of how to do it? Thank you

**Comment by Ino-Ichan** [comment]
Here is the snippet.
![image](https://user-images.githubusercontent.com/37664066/172274660-2deb363c-ddc4-4abc-902e-fdcda61862c9.png)

See also [2.3.2 8 Hz navigation rate application](https://content.u-blox.com/sites/default/files/ZED-F9P-MovingBase_AppNote_%28UBX-19009093%29.pdf)

I succeeded in setting 8 Hz, but failed to return to 1 Hz setting by this way... So please be careful.
You can get more information about u-center than writing directly through serial port, again I recommend you to find the way that u-center runs stably.

**Comment by tensorturtle** [comment]
@Ino-Ichan It worked! Thank you very much. I had to give it a few tries, and needed to reconnect with a higher baudrate (460800). It runs at 8Hz now.
