### ISSUE TITLE
how to know the accuracy 

### ISSUE THREAD

**Issue by lurunawjan** [sparkfun/Qwiic_Ublox_Gps_Py#24]
Hello, I have a project about tracking a vehicles in real time. Currently I'm using Sparkfun ZED-F9R for the GPS module and google maps API. I manage to get the coordinates with google maps in real time but I wondering about the accuracy. 

Thank you.

**Comment by grwells** [comment]
In the [Arduino version of the ublox library](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/tree/main) I was able to dig around and find `getHorizontalDOP()` (horizontal dilution of precision) which gives a rough accuracy range in millimeters (I think). The same doesn't seem to be built into the library here.

I think you need the UBX DOP message, which I don't see a default helper function for requesting and parsing. I think you are going to have to write your own code... something like the `satellites(...)` function in ublox_gps.py which requests the message from the receiver and then scales the data. So something like 5 lines of code to try out.

**Comment by edspark** [comment]
I've added a function in this [commit](https://github.com/sparkfun/Qwiic_Ublox_Gps_Py/commit/6af66b200562d5f5ac73a6af668bf7f9b6768e40) for checking accuracy. I'll be updating examples and documentation over the next few days.

**Comment by grwells** [comment]
Great! Thanks.
