### ISSUE TITLE
Sample rate is too low

### ISSUE THREAD

**Issue by mayukh4** [sparkfun/Qwiic_Ublox_Gps_Py#27]
The datasheet shows that the ZED-F9R dead reckoning board can sample anywhere between 20-30 Hz. I can't get that working with the Ublox library. Did any of you get around this? At least using some of the example codes I seem only to get 1 Hz.

**Comment by smithan7** [comment]
Same

**Comment by mayukh4** [comment]
I got around this issue, by basically connecting the board to the Ublox U-center application and configuring the sampling frequency from there. It sends config files to the flash memory of the board. However, overall for some reason working smoothly with these boards on a pi has been a struggle.
