### ISSUE TITLE
Example code Test import error

### ISSUE THREAD

**Issue by bashford1** [sparkfun/Qwiic_Ublox_Gps_Py#3]
Followed guide through the download of all software. When i try to run the sample code given "https://github.com/sparkfun/Qwiic_Ublox_Gps_Py/#example-use" , i get an import error stating no module named ublox_gps.

Thanks for your help

**Comment by marmarrz** [comment]
I'm having this same issue, what was the fix for you?

**Comment by bashford1** [comment]
On your Rpi, go to chromium and download the zips from the tutorial directly, rather than using sudo commands.

**Comment by edspark** [comment]
@bashford1 thanks for filing an issue and I'm glad you got it working. However, the issue has been resolved and you can now install with pip. If you have version 1.1.3 then you're in the right place.
