### ISSUE TITLE
Example Use code module import issue

### ISSUE THREAD

**Issue by marmarrz** [sparkfun/Qwiic_Ublox_Gps_Py#4]
After installing everything, when I try to run the Example Use code i get an error saying `no module name ublox_gps`

**Comment by edspark** [comment]
Very sorry, the module has been updated and tested to work. Either try again with another `pip install sparkfun-ublox-gps` or `pip install sparkfun-ublox-gps --upgrade`. If you have version 1.1.3, then you are in the right place.
