### ISSUE TITLE
Hardware setup

### ISSUE THREAD

**Issue by marmarrz** [sparkfun/Qwiic_Ublox_Gps_Py#6]
I'm honestly not sure if I have the hardware setup correctly. Is there documentation that explains how to get it interfacing properly? To my understanding I have everything working, but any test script I run hangs on the "Listening for UBX Packets" loop.

**Comment by edspark** [comment]
Yes there is, we have great documentation [here](https://learn.sparkfun.com/tutorials/sparkfun-gps-rtk-dead-reckoning-zed-f9r-hookup-guide) (assuming you have the F9R). If you have additional questions, then the best place to go is our [forums](https://forum.sparkfun.com/).
