### ISSUE TITLE
name 'hMSLHp' is not defined

### ISSUE THREAD

**Issue by DanNsk** [sparkfun/Qwiic_Ublox_Gps_Py#9]
Cannot retrieve high precision coordinates, because variable read on line 624 of ublox_gps.py is hMSLHp, supposed to be height_sea (as on line 615) , but parameter name supposed to be hMSLHp .
so 

>         nav_payload = nav_payload._replace(height_sea=hMSLHp * 0.1)

needs to be changed to 

>        nav_payload = nav_payload._replace(hMSLHp = height_sea * 0.1)

**Comment by LarsJaeger** [comment]
I can confirm.

**Comment by wcb-keshav** [comment]
How have they not corrected this yet!

**Comment by edspark** [comment]
This is fixed, thanks @DanNsk
